name: go_surf
channels:
  - pytorch3d
  - bottler
  - iopath
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - blosc=1.21.0=h8c45485_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.6.15=py39h06a4308_0
  - cffi=1.15.0=py39hd667e15_1
  - cfitsio=3.470=hf0d0db6_6
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.0=py39h27cfd23_0
  - dask-core=2022.5.0=py39h06a4308_0
  - dbus=1.13.6=he372182_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - fsspec=2022.3.0=py39h06a4308_0
  - fvcore=0.1.5.post20220512=pyhd8ed1ab_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=hf484d3e_1000
  - idna=3.3=pyhd3eb1b0_0
  - imagecodecs=2021.8.26=py39h4cda21f_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - iopath=0.1.9=py39
  - jpeg=9e=h7f8727e_0
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.4.2=py39h295c915_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcurl=7.82.0=h0b77cf5_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h74e7548_0
  - libzopfli=1.0.3=he6710b0_0
  - locket=1.0.0=py39h06a4308_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.2=py39hf3d152e_0
  - matplotlib-base=3.5.2=py39h700656a_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py39h06a4308_0
  - numpy=1.22.3=py39he7a7128_0
  - numpy-base=1.22.3=py39hf524024_0
  - nvidiacub=1.10.0=0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.2.0=py39hace64e9_1
  - pip=22.1.2=py39h06a4308_0
  - portalocker=2.5.1=py39hf3d152e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.9.2=py39h2531618_6
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.12=h12debd9_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.6.2=py39_cu113_pyt1110
  - pywavelets=1.3.0=py39h7f8727e_0
  - pyyaml=6.0=py39hb9d737c_4
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py39h06a4308_0
  - scikit-image=0.19.2=py39h51133e4_0
  - scipy=1.7.3=py39hc147768_0
  - setuptools=61.2.0=py39h06a4308_0
  - sip=4.19.13=py39h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sqlite=3.38.5=hc218d9a_0
  - tabulate=0.8.10=pyhd8ed1ab_0
  - termcolor=1.1.0=pyhd8ed1ab_3
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.11.0=py39_cu113
  - torchvision=0.12.0=py39_cu113
  - tqdm=4.64.0=pyhd8ed1ab_0
  - trimesh=3.12.8=pyh6c4a22f_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.9=py39h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h7f8727e_1
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zfp=0.5.5=h295c915_6
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.2.0
    - addict==2.4.0
    - anyio==3.6.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - babel==2.10.3
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cachetools==5.2.0
    - debugpy==1.6.2
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.16.1
    - google-auth==2.9.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - importlib-metadata==4.12.0
    - ipykernel==6.15.1
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.1
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - json5==0.9.8
    - jsonschema==4.7.2
    - jupyter-client==7.3.4
    - jupyter-core==4.11.1
    - jupyter-packaging==0.12.2
    - jupyter-server==1.18.1
    - jupyterlab==3.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.15.0
    - jupyterlab-widgets==1.1.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclassic==0.4.3
    - nbclient==0.6.6
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - notebook==6.4.12
    - notebook-shim==0.1.0
    - oauthlib==3.2.0
    - open3d==0.15.2
    - opencv-contrib-python==4.6.0.66
    - pandas==1.4.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.30
    - protobuf==3.19.4
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.12.0
    - pyquaternion==0.9.9
    - pyrsistent==0.18.1
    - pytz==2022.1
    - pyzmq==23.2.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.1.1
    - send2trash==1.8.0
    - git+https://github.com/tymoteuszb/smooth-sampler
    - sniffio==1.2.0
    - soupsieve==2.3.2.post1
    - stack-data==0.3.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tomlkit==0.11.1
    - tornado==6.2
    - traitlets==5.3.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.3
    - werkzeug==2.1.2
    - widgetsnbextension==3.6.1
    - zipp==3.8.1
